name: Deploy Personal site

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: enriikke/gatsby-gh-pages-action@v2.2.0
        with:
          access-token: ${{ secrets.DEPLOY_PERSONAL_SITE }}
          deploy-branch: gh-pages
    